#!/bin/bash
n=1; echo -n "$n "
let "n = $n + 1"
echo -n "$n "

echo ""

: $((n = $n + 1))
echo -n "$n "



echo ""
(( n = n + 1))
echo -n "$n "


echo""
n=$(($n + 1))
echo -n "$n "

echo""
let "n++"
echo -n "$n "



echo ""
((n++))
echo -n "$n "
echo ""
