#!/usr/bin/env bash
# This bash script transfer file from client to server
# $1 rep file dir, $2 rep ip addr of the server, $3 rep username &
# $4 rep dir of private key where pub is goon read

if [ $# -lt 3 ]; then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
