#!/usr/bin/env bash
#bash script that configure server with some requirements

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx reload
