#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is 
#redirecting to another page.

sudo apt update -y
sudo apt install nginx -y
sudo chmod -R 755 /var/www/html
echo "Hello World!" >> var/www/html/index.html
redirection="location /redirect_me {\\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}"
sudo sed -i "/listen 80 default_server/a $redirection" etc/nginx/sites-available/default
sudo service nginx start
