#!/usr/bin/env bash
#This script install nginx web server and configure it

sudo apt update -y
sudo apt-get -y install nginx
echo "Hello World!" >> /var/www/html/index.html
redirection="location /redirect_me {\\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}"
sudo sed -i "/listen 80 default_server/a $redirection" /etc/nginx/sites-available/default
sudo service nginx restart
