#!/usr/bin/env bash
#configure for 404 page

sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" > index.html
sudo mv index.html /var/www/html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.demystik.tech;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx reload
