#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is 
#redirecting to another page.

sudo apt update -y
sudo apt install nginx -y
#sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/default > /dev/null
redirection="location /redirect_me {\\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}"
sudo sed -i "/server/a $redirection" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
sudo sed -i '/^\s*server\s*{/a \        error_page 404 /404.html;\n        location = /404.html {\n            internal;\n        }' /etc/nginx/sites-available/default

sudo service nginx reload
