#!/usr/bin/env bash
#Configure nginx with a response that contains response header

sudo apt update -y
sudo apt install nginx -y
sudo chmod -R 755 /var/www/html
echo "Hello World!" >> /var/www/html/index.html
redirection="location /redirect_me {\\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}"
sudo sed -i "/listen 80 default_server/a $redirection" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" >> 404.html
sudo mv 404.html /var/www/html
sudo sed -i '/^\s*server\s*{/a \        error_page 404 /404.html;\n        location = /404.html {\n            internal;\n        }' /etc/nginx/sites-available/default

sudo sed -i '/location \/ {/a \        add_header X-Served-By "$HOSTNAME";' /etc/nginx/sites-available/default
sudo service nginx restart
