#!/usr/bin/env bash
#This short file to  fix listen port issue on sites-enabled file

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
