#!/usr/bin/env bash
# This file does this and that
i=1
while [ $i -lt 101 ]
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "fizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
