#!/usr/bin/env bash
#install ufw firewall and setup a few rules on web-01

sudo apt update -y
sudo apt install ufw -y
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
